# This file was generated by GoReleaser. DO NOT EDIT.
cask "tracelines" do
  version "1.1.3-rc1"

  on_macos do
    on_arm do
      sha256 "346b99a5f97a41998f4d95eb4ba7cc435171e8debbd2785421a292a16bda4c0b"
      url "https://github.com/f39d/tracelines/releases/download/v#{version}/tracelines_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "06c3f9226a3c3847b1b9aedd50bfc4b7770806935b09269990ff34d482f24b69"
      url "https://github.com/f39d/tracelines/releases/download/v#{version}/tracelines_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "80e82238ef69027cff1f42738ffa8ae2d88a3eb9fbef746ef54cbd44cd403c2f"
      url "https://github.com/f39d/tracelines/releases/download/v#{version}/tracelines_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b3128696850cc6925e7b61ff9a217bd0f53fe92f18b0d19ae6d30295c8d0dfc8"
      url "https://github.com/f39d/tracelines/releases/download/v#{version}/tracelines_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tracelines"
  desc "Traceability-as-code CLI for pipelines and local git workflows"
  homepage "https://github.com/f39d/tracelines"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tracelines"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/foo"]
    end
  end

  # No zap stanza required
end
